name: 'german_collocations'
services:
  db:
    image: postgres:18
    container_name: collocations-db
    environment:
      POSTGRES_DB: collocations
      POSTGRES_USER: app
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U app -d collocations']
      interval: 5s
      timeout: 3s
      retries: 5

  migrate:
    build:
      context: .
      dockerfile: database/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://app:${DB_PASSWORD}@db:5432/collocations
    command: ['npm', 'run', 'migrate']

  loader:
    build:
      context: .
      dockerfile: database/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://app:${DB_PASSWORD}@db:5432/collocations
    volumes:
      - ./data:/data:ro        # bind-mount your raw Leipzig files here
    command: ['npm', 'run', 'load-data']
    profiles: ['manual']       # keeps it from running on every `up`

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    depends_on:
      db: 
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://app:${DB_PASSWORD}@db:5432/collocations
    ports:
      - '3000:3000'
  
  frontend:
    build: 
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/app/frontend
      - ./types:/app/types
      - /app/node_modules
    environment:
      VITE_API_URL: http://localhost:3000
    depends_on:
      - backend

  extract-examples:
    build:
      context: .
      dockerfile: database/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
        DATABASE_URL: postgres://app:${DB_PASSWORD}@db:5432/collocations
    volumes:
      - ./data:/data:ro
    command: ['node', 'scripts/extract-examples.ts']
    profiles:
      - manual

volumes:
  postgres_data:
